name: Ensure + Build + Deploy React app to Azure Web App - pitcoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Ensure React app exists
        run: |
          if [ ! -d "react-spa-bootstrap" ] || [ -z "$(ls -A react-spa-bootstrap 2>/dev/null)" ]; then
            echo "Creating new React app in react-spa-bootstrap..."
            npx create-react-app@latest react-spa-bootstrap
          fi

      - name: Customize app if needed
        run: |
          cd react-spa-bootstrap
          npm install bootstrap react-bootstrap
          # Optionally inject Bootstrap Navbar, Carousel, and Footer into App.js here

      - name: Build React app
        run: |
          cd react-spa-bootstrap
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd react-spa-bootstrap
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38D69F2F6AC64FE9963783A5F27A299B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E64153AF9F434FC58AFCCB8A2486BB43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_139DD64B3A3B4D0BA8A32E72384A8993 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pitcoapp'
          slot-name: 'Production'
          package: .
