name: Build & Deploy React App with Backend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies & build
        run: |
          # cd react-spa-bootstrap
          npm install
          npm run build

      - name: Zip for deployment
        run: |
          # cd react-spa-bootstrap
          zip -r ../release.zip * .*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Unzip artifact
        # run: unzip release.zip -d ./react-spa-bootstrap
        run: unzip release.zip -d ./

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38D69F2F6AC64FE9963783A5F27A299B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E64153AF9F434FC58AFCCB8A2486BB43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_139DD64B3A3B4D0BA8A32E72384A8993 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pitcoapp'
          slot-name: 'Production'
          # package: ./react-spa-bootstrap
          package: ./