
name: Ensure + Build + Deploy React app to Azure Web App - pitcoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Ensure React app exists
        run: |
          if [ ! -d "react-spa-bootstrap" ] || [ -z "$(ls -A react-spa-bootstrap 2>/dev/null)" ]; then
            npx create-react-app@latest react-spa-bootstrap
          fi

      - name: Install Bootstrap and inject layout
        run: |
          cd react-spa-bootstrap
          npm install bootstrap react-bootstrap

          cat > src/App.js <<'EOF'
import React from 'react';
import { Navbar, Container, Nav, Carousel, Row, Col } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';

function App() {
  return (
    <div>
      <Navbar bg="dark" variant="dark" expand="lg">
        <Container>
          <Navbar.Brand href="#home">PACE IT</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link href="#home">Home</Nav.Link>
              <Nav.Link href="#about">About</Nav.Link>
              <Nav.Link href="#contact">Contact</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>

      <Carousel>
        <Carousel.Item>
          <img className="d-block w-100" src="https://via.placeholder.com/1200x400?text=Welcome+to+PACEIT" alt="Slide 1" />
          <Carousel.Caption>
            <h3>Empowering Tech</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </Carousel.Caption>
        </Carousel.Item>
        <Carousel.Item>
          <img className="d-block w-100" src="https://via.placeholder.com/1200x400?text=Innovate+Faster" alt="Slide 2" />
          <Carousel.Caption>
            <h3>Innovation at Speed</h3>
            <p>Building smarter solutions for tomorrow.</p>
          </Carousel.Caption>
        </Carousel.Item>
      </Carousel>

      <Container className="my-5">
        <h2 className="mb-4">Our Services</h2>
        <Row>
          {[1, 2, 3, 4, 5, 6].map((item) => (
            <Col key={item} md={4} className="mb-4">
              <div className="card">
                <img src={`https://via.placeholder.com/300x200?text=Service+${item}`} className="card-img-top" alt={`Service ${item}`} />
                <div className="card-body">
                  <h5 className="card-title">Service {item}</h5>
                  <p className="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
              </div>
            </Col>
          ))}
        </Row>
      </Container>

      <footer className="bg-dark text-white text-center p-4">
        &copy; 2025 PACE IT. All rights reserved.
      </footer>
    </div>
  );
}

export default App;
EOF

      - name: Build React app
        run: |
          cd react-spa-bootstrap
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd react-spa-bootstrap
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38D69F2F6AC64FE9963783A5F27A299B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E64153AF9F434FC58AFCCB8A2486BB43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_139DD64B3A3B4D0BA8A32E72384A8993 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pitcoapp'
          slot-name: 'Production'
          package: .
